import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/contexts/providers";
import Navbar from "@/components/nav/Navbar";
import {ReactQueryDevtools} from '@tanstack/react-query-devtools'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background-primary text-text-primary">
        <Providers>
          <Navbar />
          <div className="w-full md:w-[800px] mx-auto">
            {children}
            <br/>
            <br/>
            <br/>
          </div>
          <ReactQueryDevtools/>
        </Providers>
      </body>
    </html>
  );
}
