# Generated by Django 5.0.8 on 2024-08-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_popularity_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Hidden', 'Hidden'), ('Banned', 'Banned')], default='Draft', max_length=15, null=True),
        ),
    ]
